### ISSUE TITLE
BUG - Programmatic usage of `ui5-proxy-middleware` does not work

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#405] opened 2022-03-23 13:25 UTC
### Related Feature
Feature request: #228

### Description
I have tried using the `@sap-ux/ui5-proxy-middleware` in a CAP project programmatically by extending the `server.js` but it crashes (I assume) when trying to log because the logger is undefined when not running as part of the ui5 tooling. This issue should be independent of CAP and should be reproducible with any standalone `express` instance.

My sample code:
```javascript
const cds = require('@sap/cds');
const ui5Proxy = require('@sap-ux/ui5-proxy-middleware').ui5Proxy;

cds.on('bootstrap', (app) => {
    app.get('/resources/*', ui5Proxy({
        path: [
            '/resources', '/test-resources'
        ],
        url: 'https://ui5.sap.com'
    }));
});

// Delegate bootstrapping to built-in server.js of CDS
module.exports = cds.server
```
### Steps to Reproduce
1. Use any CAP project and add the snippet above to your `server.js`
2. Execute `cds run`
3. Open your browser with http://localhost:4004/resources/sap-ui-core.js
4. See error in the console

### Expected results
The browser returns the content of https://ui5.sap.com/resources/sap-ui-core.js

### Actual results
Console error:
```
[INTERNAL ERROR] TypeError: Cannot read property 'info' of undefined
    at Colorizer.colorize (/xxx/ui5-cap-event-app/node_modules/@sap-ux/logger/node_modules/logform/colorize.js:72:43)
```

### Screenshots
Not required

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment] 2022-03-23 13:32
Here is the project that I used for testing: https://github.com/tobiasqueck/ui5-cap-event-app/tree/ui5-proxy

**Comment by zdravko-georgiev** [comment] 2022-03-23 15:21
One can easily reproduce the issue just by executing this code
```Javascript
const logger = require("@sap-ux/logger");
const myLogger = new logger.ToolsLogger({
  transports: [
    new logger.UI5ToolingTransport({ moduleName: "ui5-proxy-middleware" }),
  ],
});
myLogger.info("Hello");
```
@ullasholla could you please advise?

**Comment by zdravko-georgiev** [comment] 2022-03-23 16:01
Further findings, if one uses the `ui5-proxy-middleware` as a middleware, then this issue is not occurring although the `@sap-ux/logger` is initialised the same way... 🤔

**Comment by zdravko-georgiev** [comment] 2022-03-24 16:11
@tobiasqueck @ullasholla I believe that I found the root cause of the issue. In the `node_modules` I can see that `logform` is installed twice. Once under `/node_modules/logform` and once under `/node_modules/@sap-ux/logger/node_modules/logform`. This breaks the initialisation of the `logform` package.

Furthermore this issue happens currently with `yarn`. When I use `npm` then `logform` is installed only once.
Maybe this is related to the fact how dependencies are resolved by `yarn`?

Also in the `package.json` of the `@sap-ux/logger` we have

```JSON

  "dependencies": {
      "chalk": "4.1.2",
      "lodash": "4.17.21",
      "logform": "2.3.2",
      "winston": "3.3.3",
      "winston-transport": "4.4.1"
  }
```

BUT `winston` and `winston-transport` also have dependecy to `logform` which is defined like this 
```JSON
"logform": "^2.2.0"
```


So maybe we need to remove the `logform` dependency from the `@sap-ux/logger`? Please share your thoughts.

**Closed** 2022-03-28 16:44 UTC
Labels: bug, logger
