### ISSUE TITLE
BUG - Deployment test mode stopped working on version @sap/ux-ui5-tooling:1.13.2

### ISSUE THREAD

**Issue by eurushibata** [SAP/open-ux-tools#1873] opened 2024-04-28 15:28 UTC
### Related Feature
Feature request: _issue number_

### Description
Since upgrading to @sap/ux-ui5-tooling version 1.13.2, the deploy command with test mode stopped.

### Steps to Reproduce
try to deploy with test mode to ABAP system.

```bash
fiori deploy --config ui5-deploy.yaml --testMode -- -y
```

### Expected results
Expect the deployment test to finish.  On version 1.13.1:
```
> fiori deploy --config ui5-deploy.yaml --testMode -- -y
info abap-deploy-task /SLSUI/SET_PAR2 Creating archive with UI5 build result.
info abap-deploy-task /SLSUI/SET_PAR2 Archive created.
info abap-deploy-task /SLSUI/SET_PAR2 Starting to deploy in test mode.
info abap-deploy-task /SLSUI/SET_PAR2 /SLSUI/SET_PAR2 found on target system: true
info abap-deploy-task /SLSUI/SET_PAR2 Test run has indicated no problems
info abap-deploy-task /SLSUI/SET_PAR2 ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 Running in test mode: Upload operations are indicated but not excuted, detailed log
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 93 Files found in Archive.
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 * Parameters *
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 The file '.Ui5RepositoryTextFiles' is considered to identify text files.
info abap-deploy-task /SLSUI/SET_PAR2 The binary files are identified using the standard settings.
info abap-deploy-task /SLSUI/SET_PAR2 The files and folders to be ignored are determined from the built-in standard settings.
info abap-deploy-task /SLSUI/SET_PAR2 The name of the SAPUI5 repository "/SLSUI/SET_PAR2" has been determined from the corresponding import parameter.
info abap-deploy-task /SLSUI/SET_PAR2 Transport Request "SGHK001857" has been determined from the corresponding import parameter.
info abap-deploy-task /SLSUI/SET_PAR2 The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
info abap-deploy-task /SLSUI/SET_PAR2 The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
info abap-deploy-task /SLSUI/SET_PAR2 Unix style end of line markers in text files get accepted.
info abap-deploy-task /SLSUI/SET_PAR2 The delta mode has been turned on.
info abap-deploy-task /SLSUI/SET_PAR2 Running in safe mode
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 * Operations *
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : .Ui5RepositoryTextFiles (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component-dbg.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component-preload.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component-preload.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component.d.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component.d.ts.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : Component.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController-dbg.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController.d.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController.d.ts.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/BaseController.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/chooseOptionStep-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/chooseOptionStep.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/chooseOptionStep.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/configureParametersStep-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/configureParametersStep.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/configureParametersStep.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ErrorHandler-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ErrorHandler.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ErrorHandler.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/Main-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/Main.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/Main.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/paramConfig-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/paramConfig.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/paramConfig.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration-dbg.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration.controller.d.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration.controller.d.ts.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/ParameterConfiguration.controller.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/SetParameters-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/SetParameters.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/SetParameters.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/summaryStep-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/summaryStep.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/summaryStep.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/transAreaSettings-dbg.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/transAreaSettings.controller.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : controller/transAreaSettings.controller.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : css/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : css/styles.css (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : i18n/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : i18n/i18n_en_IE.properties (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : i18n/i18n_en.properties (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : index.d.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : manifest.json (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : mockdata.json (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/dataHelper-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/dataHelper.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/dataHelper.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces-dbg.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces.d.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces.d.ts.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/interfaces.ts (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/mapper-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/mapper.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/mapper.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/models-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/models.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/models.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/validator-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/validator.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : model/validator.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : resources.json (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : sap-ui-cachebuster-info.json (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : utils/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : utils/formatter-dbg.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : utils/formatter.js (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : utils/formatter.js.map (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/chooseOptionStep.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/configureParametersStep.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/fragment/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/fragment/addDevSystemDialog.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/fragment/configTrans.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/fragment/generalConfig.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/fragment/transAreaDialog.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/fragment/worklistInfo.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/Main.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/paramConfig.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/ParameterConfiguration.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/popover/ (Folder already exists)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/popover/CollectionsPopover.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/popover/DevSysPopover.fragment.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/SetParameters.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/summaryStep.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 NONE          : view/transAreaSettings.view.xml (Text) (Already up-to-date)
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 Test run has indicated no problems
info abap-deploy-task /SLSUI/SET_PAR2 
info abap-deploy-task /SLSUI/SET_PAR2 * Done *
info abap-deploy-task /SLSUI/SET_PAR2 Deployment in TestMode completed. A successful TestMode execution does not necessarily mean that your upload will be successful.
```

### Actual results
On version 1.13.2:
```
  > fiori deploy --config ui5-deploy.yaml --testMode -- -y
  info abap-deploy-task /SLSUI/SET_PAR2 Creating archive with UI5 build result.
  info abap-deploy-task /SLSUI/SET_PAR2 Archive created.
  info abap-deploy-task /SLSUI/SET_PAR2 Starting to deploy in test mode.
  error abap-deploy-task /SLSUI/SET_PAR2 Deployment has failed.
  error abap-deploy-task /SLSUI/SET_PAR2 Change logging level to debug your issue
  error abap-deploy-task /SLSUI/SET_PAR2  (see examples https://github.com/SAP/open-ux-tools/tree/main/packages/deploy-tooling#configuration-with-logging-enabled)
  error builder:custom deploy-to-abap client.trim is not a function
  Command deploy failed with error : client.trim is not a function
```

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by longieirl** [comment] 2024-04-29 16:14
Hi,

I'm struggling to reproduce the issue both locally on mac and on Business Application Studio using either 1.13.2 and the latest 1.13.3.

Can you share your ui5-deploy.yaml please? Please obfuscate any sensitive data please. Do you know the reason why the HTTP request is failing as I might be able to reduce the HTTP error code to understand the flow more.

You can also add more verbose logging, by adding the verbose flag;
```YAML
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        verbose: true
        target: ...
```
Thanks.
John

**Comment by eurushibata** [comment] 2024-04-29 19:31
Hi John, I am using vscode on macos.

I was not able to determine, even raising the log level to 5 as it stops here:
```
error builder:custom deploy-to-abap client.trim is not a function
```

here it goes my ui5-build.yaml
```
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "3.1"
type: application
metadata:
  name: gsslsui.environment.set_up_param2
  copyright: |-
    SOL UI - https://github.wdf.sap.corp/SAPLanguagePlatform/SolUIs
    * (c) Copyright 2017-${currentYear} SAP
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
    paths:
      webapp: webapp
framework:
  name: SAPUI5
  version: 1.96.17
builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        target:
          url: xxxxx
          client: 000
          auth: basic
        credentials:
          username: env:FIORI_TOOLS_USER
          password: env:FIORI_TOOLS_PASSWORD
        app:
          name: /SLSUI/SET_PAR2
          description: Set the parameters for an evaluation 2
          package: /SLSUI/UI_ENVIRONMENT
          transport: xxxxx
        exclude:
          - /test/
```


If you need more information on reproducing, please message me on SAP MSteams.

**Comment by eurushibata** [comment] 2024-04-30 15:01
@longieirl thank you for the first analysis.

The error does make sense as if there is possibily a boolean verification against the client field:
```
  if (target.client) {
      ...
   } )
```
it will return as boolean false and therefore could be the reason of this error. Well definitelly something on this version changed as we've always used without quotes.

I'll stick with the older version for now and wait what is the resolution.

Thank you,
Emerson

**Comment by longieirl** [comment] 2024-04-30 15:25
Hi,
Here is some code to replicate the issue;

```Typescript
import { parseDocument } from 'yaml';
import { readFileSync } from 'fs';
import { join } from 'path';

const yaml = parseDocument(readFileSync(join(process.cwd(), 'ui5-deploy.yaml'), 'utf8')).toJSON();

console.log(`>>> ${JSON.stringify(yaml)}`);
```

The `parseDocument` method is returning 0 instead of 000 and then in the deploy-tooling, the client is passed as an integer instead of a string;

https://github.com/SAP/open-ux-tools/blob/2c4de8cb846364b6e323fd2b7008bfdb0c8b6a85/packages/store/src/entities/backend-system.ts#L64

There are two fixes required;

In `@sap/ux-ui5-tooling` when we parse the yaml document, pad out the value and also apply more validation in deploy-tooling when handling the input parameters.

**Comment by longieirl** [comment] 2024-04-30 15:38
Also, when you create the deployment config using the SAP Fiori tools wizard, it will create the following configuration with the client correctly quoted;
```
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        target:
          url: https://myabaphost:44300
          client: "000"
        app:
          name: TEST
          package: $tmp
          transport: ""
        exclude:
          - /test/
  ```
However, the fixes still need to be applied to prevent this exception if the yaml configuration is manually changed.

**Comment by longieirl** [comment] 2024-05-01 10:25
@eurushibata what is strange, I'm able to reproduce this issue on all versions i.e. 1.13.1 and 1.11.5. 

To ensure this value is correctly handled i.e. the appropiate client ID is passed to any HTTP calls, I would ensure that its double quoted. For example, if you search for any YAML formatters online it will change 000 to 0 which is not the correct client ID when passed to the ABAP backend.

**Comment by mikicvi-SAP** [comment] 2024-06-11 07:04
Hi @eurushibata, this issue is fixed with the latest version of `@sap/ux-ui5-tooling:1.13.6`.
Closing as completed and validated internally.

**Closed by mikicvi-SAP** 2024-06-11 07:04 UTC
Labels: bug, deploy-tooling
